//! The MCP server handler: the tool + resource surface.
//!
//! Tools are declared with rmcp's `#[tool_router]`/`#[tool]`/`#[tool_handler]`
//! macros. Every handler resolves the request's authenticated user (injected by
//! [`super::auth`]) and delegates to the same ACL-checked handlers the REST
//! routes use, constructing their axum extractors directly — so the MCP surface
//! and the HTTP surface share one implementation and one permission model.

use std::marker::PhantomData;

use axum::extract::{Path, Query, State};
use axum::Json;
use axum_extra::extract::WithRejection;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::{
    CallToolResult, ContentBlock, ListResourceTemplatesResult, ListResourcesResult,
    PaginatedRequestParams, ReadResourceRequestParams, ReadResourceResponse, ReadResourceResult,
    Resource, ResourceContents, ResourceTemplate, ServerCapabilities, ServerConfig,
};
use rmcp::service::RequestContext;
use rmcp::{tool, tool_handler, tool_router, ErrorData as McpError, RoleServer, ServerHandler};
use serde::Deserialize;
use serde_json::json;

use rust_note_core::frontmatter::Frontmatter;
use rust_note_core::leads::{Kind, PipelineItem};

use super::auth::AuthUser;
use crate::auth::session::RequireAuth;
use crate::collab::write::edit_note_through_room;
use crate::error::{AppError, AppResult};
use crate::notes::acl;
use crate::notes::fs_store::{is_valid_note_id, note_id_to_path, slugify_note_id};
use crate::state::AppState;

/// Note-id prefix every pipeline item lives under.
const PIPELINE_PREFIX: &str = "pipeline/";

/// One MCP server instance. A fresh one is built per session by the service
/// factory (see [`super::service`]), each capturing process-wide [`AppState`].
///
/// Note there is deliberately no `tool_router` field: rmcp's `#[tool_handler]`
/// dispatches through the *static* `Self::tool_router()` (generated by
/// `#[tool_router]`), so an instance field would be dead weight.
pub struct McpServer {
    state: AppState,
}

// ---- request-scoped identity ----------------------------------------------

/// Pull the authenticated `user_id` the auth middleware stashed. The rmcp
/// transport forwards the whole `http::request::Parts` into the request
/// context; our [`AuthUser`] lives inside its extensions.
fn require_user(ctx: &RequestContext<RoleServer>) -> Result<String, McpError> {
    let parts = ctx
        .extensions
        .get::<axum::http::request::Parts>()
        .ok_or_else(|| McpError::internal_error("missing request context", None))?;
    let user = parts
        .extensions
        .get::<AuthUser>()
        .ok_or_else(|| McpError::invalid_params("unauthenticated", None))?;
    Ok(user.0.clone())
}

// ---- result helpers -------------------------------------------------------

/// Wrap a serializable value as a single JSON text content block.
fn json_ok<T: serde::Serialize>(value: &T) -> Result<CallToolResult, McpError> {
    let text = serde_json::to_string_pretty(value)
        .map_err(|e| McpError::internal_error(format!("serialize: {e}"), None))?;
    Ok(CallToolResult::success(vec![ContentBlock::text(text)]))
}

/// Map an [`AppError`] to a client-visible tool error, mirroring the REST
/// error mapping (internal details are logged, never leaked to the client).
fn app_error_to_tool(err: AppError) -> CallToolResult {
    if let AppError::Internal(e) = &err {
        tracing::error!(error = ?e, "mcp tool internal error");
    }
    let message = match &err {
        AppError::Internal(_) => "internal error".to_string(),
        other => other.to_string(),
    };
    CallToolResult::error(vec![ContentBlock::text(message)])
}

/// Settings notes (`_settings/<user>/…`) hold secrets (OpenRouter key) and app
/// internals; they are never exposed through the MCP surface.
fn is_settings_id(id: &str) -> bool {
    id == "_settings" || id.starts_with("_settings/")
}

/// The task-line grammar, exposed as the `todo://grammar` resource so a client
/// LLM can author valid tasks and build filters without a server round-trip.
const TODO_GRAMMAR: &str = "\
# rust_note task-line grammar

Tasks are markdown checkbox lines inside a note (daily notes are `diary/YYYY-MM-DD`):

    - [ ] open task   ·   - [x] done task

Inline tokens (any order, after the text):
- Burner priority via a tag: `#fb` / `#frontburner`, `#bb` / `#backburner`, `#fridge`, `#oven`.
  Front burner = do now; back burner = soon; fridge = someday (ages/\"spoils\" after 14 days);
  oven = parked.
- `p:N`   pomodoros estimate (integer). NOTE: unrelated to YAML `pomodoros` stats.
- `start:HH:MM`   start time.
- `due:<text>`   due date/time (free text to end of line).
- `#tag`   arbitrary tags.
- `@location`   context, e.g. `@home`, `@work`, `@store` (lowercased).

Example:
    - [ ] draft the proposal #fb p:3 start:09:00 due:friday #work @office

Query/filter tokens (for the `search_notes`/board style search, applied client-side):
`@loc`, `#tag`, burner names (`fb`/`frontburner`/`bb`/`backburner`/`fridge`/`oven`),
`p>=N` / `p<=N`, and free text.";

// ---- write helpers --------------------------------------------------------

/// Append `addition` to `old`, ensuring a newline separates them and the result
/// ends with a newline.
fn append_markdown(old: &str, addition: &str) -> String {
    let mut s = old.to_string();
    if !s.is_empty() && !s.ends_with('\n') {
        s.push('\n');
    }
    s.push_str(addition);
    if !s.ends_with('\n') {
        s.push('\n');
    }
    s
}

/// Flip the state char of a markdown checkbox line (`[ ]` ⇄ `[x]`) to the
/// desired `done` state, preserving everything else. `None` if the line has no
/// recognizable `[_]` checkbox.
fn set_checkbox_state(line: &str, done: bool) -> Option<String> {
    let open = line.find('[')?;
    let state_idx = open + 1;
    let close_idx = open + 2;
    if line.as_bytes().get(close_idx) != Some(&b']') {
        return None;
    }
    let new_state = if done { 'x' } else { ' ' };
    let mut out = String::with_capacity(line.len());
    out.push_str(line.get(..state_idx)?);
    out.push(new_state);
    out.push_str(line.get(close_idx..)?);
    Some(out)
}

/// Locate the target task line and set its checkbox to `done`, returning the new
/// full document. Prefers the reported `line_hint` (1-based) when it still holds
/// a matching task, else the first task whose text matches — mirroring the
/// client's stale-line-tolerant toggle. `None` if no task matches.
fn toggle_in_text(old: &str, line_hint: Option<u32>, text: &str, done: bool) -> Option<String> {
    let tasks = rust_note_core::tasks::parse_tasks(old);
    let query = text.trim();
    let matches = |t: &rust_note_core::tasks::Task| {
        t.text.trim() == query || t.text_clean.trim() == query || t.text.contains(query)
    };
    let target = line_hint
        .and_then(|l| tasks.iter().find(|t| t.line == l as usize && matches(t)))
        .or_else(|| tasks.iter().find(|t| matches(t)))?;
    let idx = target.line.checked_sub(1)?;
    let mut lines: Vec<String> = old.split('\n').map(str::to_string).collect();
    let flipped = set_checkbox_state(lines.get(idx)?, done)?;
    *lines.get_mut(idx)? = flipped;
    Some(lines.join("\n"))
}

// ---- pipeline helpers -----------------------------------------------------

/// Set a frontmatter key only when `val` is present and non-blank (trimmed).
fn set_opt(fm: &mut Frontmatter, key: &str, val: Option<&str>) {
    if let Some(v) = val.map(str::trim).filter(|s| !s.is_empty()) {
        fm.set(key, v);
    }
}

/// Today's civil date (`YYYY-MM-DD`) in the default tracker timezone, used for
/// the `- <today> — …` timeline prefix. Matches the stats module's default-tz
/// convention (interviews/leads are local-calendar events for a one-person
/// vault).
fn today_string() -> String {
    crate::stats::fmt_date(crate::stats::today_in_tz(crate::stats::DEFAULT_TZ))
}

/// Prepend `entry` as the newest line directly under the body's `## Timeline`
/// heading. If the body has no such heading, append one (with the entry) at the
/// end. The rest of the body is preserved byte-for-byte (split/join round-trip).
fn prepend_timeline(body: &str, entry: &str) -> String {
    const HEADING: &str = "## Timeline";
    let lines: Vec<&str> = body.split('\n').collect();
    match lines.iter().position(|l| l.trim() == HEADING) {
        Some(idx) => {
            let mut out: Vec<String> = Vec::with_capacity(lines.len() + 1);
            for (i, line) in lines.iter().enumerate() {
                out.push((*line).to_string());
                if i == idx {
                    out.push(entry.to_string());
                }
            }
            out.join("\n")
        }
        None => {
            let trimmed = body.trim_end_matches('\n');
            if trimmed.is_empty() {
                format!("{HEADING}\n{entry}\n")
            } else {
                format!("{trimmed}\n\n{HEADING}\n{entry}\n")
            }
        }
    }
}

/// Render a brand-new pipeline note (frontmatter + heading + `## Timeline`
/// body) from create args. `kind_str` is the already-validated canonical kind.
fn render_new_pipeline_note(kind_str: &str, args: &CreatePipelineArgs) -> String {
    let company = args.company.trim();
    let role = args
        .role
        .as_deref()
        .map(str::trim)
        .filter(|s| !s.is_empty());

    let mut fm = Frontmatter {
        fields: Vec::new(),
        raw_extra: Vec::new(),
        body: String::new(),
    };
    fm.set("kind", kind_str);
    fm.set("company", company);
    set_opt(&mut fm, "role", role);
    set_opt(&mut fm, "stage", args.stage.as_deref());
    if let Some(ball) = args
        .ball
        .as_deref()
        .map(str::trim)
        .filter(|s| !s.is_empty())
    {
        fm.set("ball", &ball.to_ascii_lowercase());
    }
    set_opt(&mut fm, "expected_at", args.expected_at.as_deref());
    set_opt(&mut fm, "next_action", args.next_action.as_deref());
    set_opt(&mut fm, "contact", args.contact.as_deref());
    if let Some(p) = args.priority {
        fm.set("priority", &p.to_string());
    }

    let heading = match role {
        Some(r) => format!("{company} — {r}"),
        None => company.to_string(),
    };
    let mut body = format!("# {heading}\n\n");
    if let Some(note) = args
        .note
        .as_deref()
        .map(str::trim)
        .filter(|s| !s.is_empty())
    {
        body.push_str(note);
        body.push_str("\n\n");
    }
    body.push_str("## Timeline\n");
    fm.body = body;
    fm.render()
}

// ---- tool argument types --------------------------------------------------

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct SearchNotesArgs {
    /// Case-insensitive substring matched against each note's id and title.
    query: String,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct ReadNoteArgs {
    /// Note id, e.g. `diary/2026-09-29` or `projects/trip-planning`.
    id: String,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct ListTodosArgs {
    /// `diary` (default) restricts to daily notes; `all` scans every note.
    #[serde(default)]
    scope: Option<String>,
    /// Include completed tasks. Defaults to true.
    #[serde(default)]
    include_done: Option<bool>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct GetStatsArgs {
    /// Inclusive start date `YYYY-MM-DD`. Defaults to 30 days before `to`.
    #[serde(default)]
    from: Option<String>,
    /// Inclusive end date `YYYY-MM-DD`. Defaults to today (server timezone).
    #[serde(default)]
    to: Option<String>,
    /// Restrict to one metric. A parent name (e.g. `exercise`) returns a
    /// boolean "did it happen" series. Omit for the whole registered dashboard.
    #[serde(default)]
    metric: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct AppendToNoteArgs {
    /// Note id to append to (must already exist).
    id: String,
    /// Markdown to append at the end of the note.
    markdown: String,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct RecordStatArgs {
    /// Metric key, lowercase dotted (e.g. `caffeine`, `exercise.cardio`).
    key: String,
    /// Integer value (no floats).
    value: i64,
    /// Optional time as `HHMM` (24h), e.g. `0720`.
    #[serde(default)]
    at: Option<String>,
    /// Optional date `YYYY-MM-DD`; defaults to today in the server timezone.
    #[serde(default)]
    date: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct ToggleTodoArgs {
    /// The note the task lives in, e.g. `diary/2026-09-29`.
    note_id: String,
    /// The task text (raw line text or its cleaned form) — used to locate the
    /// task even if `line` is stale. Required.
    text: String,
    /// Optional 1-based line number hint from a prior `list_todos`.
    #[serde(default)]
    line: Option<u32>,
    /// Desired state: true = done (`[x]`), false = open (`[ ]`).
    done: bool,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct DefineMetricArgs {
    /// Metric key to define (lowercase dotted).
    metric: String,
    /// Display unit, e.g. `mg`, `min`.
    #[serde(default)]
    unit: Option<String>,
    /// Human label; defaults to the metric key.
    #[serde(default)]
    label: Option<String>,
    /// Chart kind: `line` | `bar` | `boolean` | `heatmap` (defaults to line).
    #[serde(default)]
    chart: Option<String>,
    /// Aggregation: `sum` | `last` | `max` | `min` | `count` (defaults to sum).
    #[serde(default)]
    agg: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct CreateNoteToolArgs {
    /// A note id or title; slugified into a note id.
    id_or_title: String,
    /// Optional initial markdown content.
    #[serde(default)]
    content: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct ListPipelineArgs {
    /// `lead` | `application`; omit for all kinds.
    #[serde(default)]
    kind: Option<String>,
    /// Include closed items (terminal stage or ball=none). Defaults to false.
    #[serde(default)]
    include_closed: Option<bool>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct CreatePipelineArgs {
    /// Company / contact org. Required.
    company: String,
    /// `lead` (a gig Rafał could do) or `application` (Rafał applied). Required.
    kind: String,
    /// Role applied for, or the gig / what-for.
    #[serde(default)]
    role: Option<String>,
    /// Pipeline stage (free text, e.g. `applied`, `interview`, `proposal`).
    #[serde(default)]
    stage: Option<String>,
    /// Whose court the ball is in: `ours` | `theirs` | `none`.
    #[serde(default)]
    ball: Option<String>,
    /// Deadline the ball should move by, RFC3339.
    #[serde(default)]
    expected_at: Option<String>,
    /// The concrete next action the ball represents.
    #[serde(default)]
    next_action: Option<String>,
    /// Comma-separated `Name <email> (role)` contact entries.
    #[serde(default)]
    contact: Option<String>,
    /// Priority 1–5 (higher = chase harder).
    #[serde(default)]
    priority: Option<u8>,
    /// Optional markdown body, inserted above the `## Timeline` section.
    #[serde(default)]
    note: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct UpdatePipelineArgs {
    /// Pipeline note id, e.g. `pipeline/affirm-senior-swe-backend`.
    id: String,
    #[serde(default)]
    company: Option<String>,
    #[serde(default)]
    kind: Option<String>,
    #[serde(default)]
    role: Option<String>,
    #[serde(default)]
    stage: Option<String>,
    #[serde(default)]
    ball: Option<String>,
    #[serde(default)]
    expected_at: Option<String>,
    #[serde(default)]
    next_action: Option<String>,
    #[serde(default)]
    contact: Option<String>,
    #[serde(default)]
    priority: Option<u8>,
    #[serde(default)]
    closed_reason: Option<String>,
}

impl UpdatePipelineArgs {
    /// Collect the supplied frontmatter keys to `set`, trimmed and non-blank.
    /// `kind`/`ball` are normalized lowercase; `priority` is stringified.
    fn frontmatter_updates(&self) -> Vec<(&'static str, String)> {
        let mut out: Vec<(&'static str, String)> = Vec::new();
        for (key, val) in [
            ("company", &self.company),
            ("role", &self.role),
            ("stage", &self.stage),
            ("expected_at", &self.expected_at),
            ("next_action", &self.next_action),
            ("contact", &self.contact),
            ("closed_reason", &self.closed_reason),
        ] {
            if let Some(v) = val.as_deref().map(str::trim).filter(|s| !s.is_empty()) {
                out.push((key, v.to_string()));
            }
        }
        if let Some(v) = self
            .kind
            .as_deref()
            .map(str::trim)
            .filter(|s| !s.is_empty())
        {
            out.push(("kind", v.to_ascii_lowercase()));
        }
        if let Some(v) = self
            .ball
            .as_deref()
            .map(str::trim)
            .filter(|s| !s.is_empty())
        {
            out.push(("ball", v.to_ascii_lowercase()));
        }
        if let Some(p) = self.priority {
            out.push(("priority", p.to_string()));
        }
        out
    }
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct LogPipelineEventArgs {
    /// Pipeline note id, e.g. `pipeline/affirm-senior-swe-backend`.
    id: String,
    /// The event text; prepended as `- <today> — <line>` under `## Timeline`.
    line: String,
    /// Optionally also set whose court the ball is in: `ours`|`theirs`|`none`.
    #[serde(default)]
    ball: Option<String>,
    /// Optionally also set the deadline (RFC3339).
    #[serde(default)]
    expected_at: Option<String>,
    /// Optionally also set the stage.
    #[serde(default)]
    stage: Option<String>,
    /// Optionally also set the next action.
    #[serde(default)]
    next_action: Option<String>,
}

#[tool_router]
impl McpServer {
    pub fn new(state: AppState) -> Self {
        Self { state }
    }

    /// Fetch the caller's readable note metadata, minus settings notes.
    async fn note_index(&self, user_id: String) -> Result<Vec<serde_json::Value>, McpError> {
        let Json(metas) =
            crate::notes::routes::list_notes(State(self.state.clone()), RequireAuth(user_id))
                .await
                .map_err(|e| match e {
                    AppError::Internal(err) => {
                        McpError::internal_error(format!("list notes: {err}"), None)
                    }
                    other => McpError::internal_error(other.to_string(), None),
                })?;
        Ok(metas
            .into_iter()
            .filter(|m| !is_settings_id(&m.id))
            .map(|m| json!({ "id": m.id, "title": m.title, "updated_at": m.updated_at }))
            .collect())
    }

    #[tool(
        description = "List all notes the user can read, as {id, title, updated_at} (no bodies)."
    )]
    async fn list_notes(
        &self,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        let user = require_user(&ctx)?;
        let index = self.note_index(user).await?;
        json_ok(&index)
    }

    #[tool(
        description = "Find notes whose id or title contains a substring (case-insensitive). \
                          Title/id search only — not full-text."
    )]
    async fn search_notes(
        &self,
        Parameters(args): Parameters<SearchNotesArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        let user = require_user(&ctx)?;
        let needle = args.query.to_lowercase();
        let matches: Vec<serde_json::Value> = self
            .note_index(user)
            .await?
            .into_iter()
            .filter(|m| {
                let hay = |k: &str| {
                    m.get(k)
                        .and_then(|v| v.as_str())
                        .map(|s| s.to_lowercase().contains(&needle))
                        .unwrap_or(false)
                };
                hay("id") || hay("title")
            })
            .collect();
        json_ok(&matches)
    }

    #[tool(description = "Read one note's content and metadata by id.")]
    async fn read_note(
        &self,
        Parameters(args): Parameters<ReadNoteArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        let user = require_user(&ctx)?;
        if is_settings_id(&args.id) {
            return Ok(CallToolResult::error(vec![ContentBlock::text(
                "settings notes are not accessible via MCP",
            )]));
        }
        match crate::notes::routes::get_note(
            State(self.state.clone()),
            RequireAuth(user),
            Path(args.id),
        )
        .await
        {
            Ok(Json(resp)) => json_ok(&resp),
            Err(e) => Ok(app_error_to_tool(e)),
        }
    }

    #[tool(
        description = "List parsed tasks across notes (burner, pomodoros, start/due, tags, \
                          locations, done). Filter client-side; see the todo://grammar resource."
    )]
    async fn list_todos(
        &self,
        Parameters(args): Parameters<ListTodosArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        use crate::todos::routes::{Scope, TodosQuery};
        let user = require_user(&ctx)?;
        let scope = match args.scope.as_deref() {
            Some("all") => Scope::All,
            _ => Scope::Diary,
        };
        let query = TodosQuery {
            scope,
            include_done: args.include_done.unwrap_or(true),
        };
        match crate::todos::routes::list_todos(
            State(self.state.clone()),
            RequireAuth(user),
            Query(query),
        )
        .await
        {
            Ok(Json(todos)) => json_ok(&todos),
            Err(e) => Ok(app_error_to_tool(e)),
        }
    }

    #[tool(
        description = "Get daily stat series over a date range (per-day aggregated value plus \
                          raw timed points). A parent metric name returns a boolean series."
    )]
    async fn get_stats(
        &self,
        Parameters(args): Parameters<GetStatsArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        use crate::stats::routes::StatsQuery;
        let user = require_user(&ctx)?;
        let query = StatsQuery {
            from: args.from,
            to: args.to,
            metric: args.metric,
        };
        match crate::stats::routes::list_stats(
            State(self.state.clone()),
            RequireAuth(user),
            Query(query),
        )
        .await
        {
            Ok(Json(resp)) => json_ok(&resp),
            Err(e) => Ok(app_error_to_tool(e)),
        }
    }

    #[tool(
        description = "List the user's registered stat metrics (metric, unit, label, chart, agg)."
    )]
    async fn list_metrics(
        &self,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        let user = require_user(&ctx)?;
        match crate::stats::routes::get_registry(State(self.state.clone()), RequireAuth(user)).await
        {
            Ok(Json(defs)) => json_ok(&defs),
            Err(e) => Ok(app_error_to_tool(e)),
        }
    }

    /// ACL for a content write to an *existing* note: require a valid id, that
    /// the note exists (adopting an on-disk orphan the app hasn't seen yet), and
    /// that the caller may write it. Mirrors the REST write path's checks.
    async fn authorize_write(&self, user: &str, note_id: &str) -> AppResult<()> {
        if !is_valid_note_id(note_id) {
            return Err(AppError::BadRequest("invalid note id".to_string()));
        }
        let db = &self.state.db;
        if !acl::note_exists(db, note_id)
            .await
            .map_err(AppError::Internal)?
        {
            let rel = note_id_to_path(note_id);
            let on_disk = self
                .state
                .notes_repo
                .read_file(&rel)
                .map_err(AppError::Internal)?
                .is_some();
            if !on_disk {
                return Err(AppError::NotFound);
            }
            acl::adopt_if_orphaned(db, note_id, user)
                .await
                .map_err(AppError::Internal)?;
        }
        if !acl::can_write(db, note_id, user)
            .await
            .map_err(AppError::Internal)?
        {
            return Err(AppError::Forbidden);
        }
        Ok(())
    }

    #[tool(
        description = "Append markdown to the end of an existing note, through its live collab \
                       room so a note open in the editor isn't clobbered."
    )]
    async fn append_to_note(
        &self,
        Parameters(args): Parameters<AppendToNoteArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        let user = require_user(&ctx)?;
        if is_settings_id(&args.id) {
            return Ok(CallToolResult::error(vec![ContentBlock::text(
                "settings notes are not writable via MCP",
            )]));
        }
        if let Err(e) = self.authorize_write(&user, &args.id).await {
            return Ok(app_error_to_tool(e));
        }
        let md = args.markdown;
        let applied = edit_note_through_room(&self.state, &args.id, &user, move |old| {
            Some(append_markdown(old, &md))
        })
        .await
        .map_err(|e| McpError::internal_error(e.to_string(), None))?;
        if applied {
            json_ok(&json!({ "id": args.id, "appended": true }))
        } else {
            Ok(CallToolResult::error(vec![ContentBlock::text(
                "append was refused",
            )]))
        }
    }

    #[tool(
        description = "Record a daily stat value (integer). Optional at:\"HHMM\" and \
                       date:\"YYYY-MM-DD\" (defaults to today, server timezone). Repeated \
                       values on a day accumulate. See the stats://docs resource."
    )]
    async fn record_stat(
        &self,
        Parameters(args): Parameters<RecordStatArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        let user = require_user(&ctx)?;
        let body = crate::stats::routes::LogRequest {
            key: args.key,
            value: args.value,
            at: args.at,
            date: args.date,
        };
        match crate::stats::routes::log_stat(
            State(self.state.clone()),
            RequireAuth(user),
            WithRejection(Json(body), PhantomData),
        )
        .await
        {
            Ok(Json(resp)) => json_ok(&resp),
            Err(e) => Ok(app_error_to_tool(e)),
        }
    }

    #[tool(
        description = "Mark a task done or open. Provide the task `text` (and optionally its \
                       1-based `line`) so it can be located even if the line moved. Writes \
                       through the collab room."
    )]
    async fn toggle_todo(
        &self,
        Parameters(args): Parameters<ToggleTodoArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        let user = require_user(&ctx)?;
        if is_settings_id(&args.note_id) {
            return Ok(CallToolResult::error(vec![ContentBlock::text(
                "settings notes are not writable via MCP",
            )]));
        }
        if let Err(e) = self.authorize_write(&user, &args.note_id).await {
            return Ok(app_error_to_tool(e));
        }
        let (line, text, done) = (args.line, args.text, args.done);
        let applied = edit_note_through_room(&self.state, &args.note_id, &user, move |old| {
            toggle_in_text(old, line, &text, done)
        })
        .await
        .map_err(|e| McpError::internal_error(e.to_string(), None))?;
        if applied {
            json_ok(&json!({ "note_id": args.note_id, "done": done }))
        } else {
            Ok(CallToolResult::error(vec![ContentBlock::text(
                "no matching task line was found",
            )]))
        }
    }

    #[tool(
        description = "Define or update a stat metric's display config so it charts in /stats: \
                       unit, label, chart (line|bar|boolean|heatmap), agg (sum|last|max|min|count)."
    )]
    async fn define_metric(
        &self,
        Parameters(args): Parameters<DefineMetricArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        let user = require_user(&ctx)?;
        let body = crate::stats::routes::RegistryUpsert {
            unit: args.unit.unwrap_or_default(),
            label: args.label.unwrap_or_default(),
            chart: args.chart.unwrap_or_default(),
            agg: args.agg.unwrap_or_default(),
        };
        match crate::stats::routes::put_registry(
            State(self.state.clone()),
            RequireAuth(user),
            Path(args.metric),
            WithRejection(Json(body), PhantomData),
        )
        .await
        {
            Ok(Json(def)) => json_ok(&def),
            Err(e) => Ok(app_error_to_tool(e)),
        }
    }

    #[tool(
        description = "Create a new note from an id or title (slugified). Fails if it already exists."
    )]
    async fn create_note(
        &self,
        Parameters(args): Parameters<CreateNoteToolArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        let user = require_user(&ctx)?;
        let body = crate::notes::routes::CreateNoteRequest {
            id_or_title: args.id_or_title,
            content: args.content,
        };
        match crate::notes::routes::create_note(
            State(self.state.clone()),
            RequireAuth(user),
            WithRejection(Json(body), PhantomData),
        )
        .await
        {
            Ok(Json(meta)) => json_ok(&meta),
            Err(e) => Ok(app_error_to_tool(e)),
        }
    }

    #[tool(
        description = "List pipeline items (leads + applications) in the same shape as GET \
                       /api/pipeline: each item flattened with a derived `overdue` bool. Filter \
                       by `kind` (lead|application); `include_closed` defaults to false."
    )]
    async fn list_pipeline(
        &self,
        Parameters(args): Parameters<ListPipelineArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        use crate::pipeline::routes::PipelineQuery;
        let user = require_user(&ctx)?;
        let query = PipelineQuery {
            kind: args.kind,
            include_closed: args.include_closed.unwrap_or(false),
        };
        match crate::pipeline::routes::list_pipeline(
            State(self.state.clone()),
            RequireAuth(user),
            Query(query),
        )
        .await
        {
            Ok(Json(items)) => json_ok(&items),
            Err(e) => Ok(app_error_to_tool(e)),
        }
    }

    /// Conflict-check, register ownership, and write a brand-new pipeline note
    /// through the collab room, returning the parsed item. Mirrors the REST
    /// create path's checks but writes through the room (never the file
    /// directly).
    async fn create_pipeline(
        &self,
        user: &str,
        note_id: &str,
        kind_str: &str,
        args: &CreatePipelineArgs,
    ) -> AppResult<PipelineItem> {
        if !is_valid_note_id(note_id) {
            return Err(AppError::BadRequest("invalid note id".to_string()));
        }
        let db = &self.state.db;
        let rel = note_id_to_path(note_id);
        let on_disk = self
            .state
            .notes_repo
            .read_file(&rel)
            .map_err(AppError::Internal)?
            .is_some();
        if on_disk
            || acl::note_exists(db, note_id)
                .await
                .map_err(AppError::Internal)?
        {
            return Err(AppError::Conflict(format!("note {note_id} already exists")));
        }
        acl::ensure_note_registered(db, note_id, user)
            .await
            .map_err(AppError::Internal)?;

        let content = render_new_pipeline_note(kind_str, args);
        let applied =
            edit_note_through_room(&self.state, note_id, user, move |_old| Some(content)).await?;
        if !applied {
            return Err(AppError::Internal(anyhow::anyhow!("write was refused")));
        }
        acl::touch_updated_at(db, note_id)
            .await
            .map_err(AppError::Internal)?;

        let text = self
            .state
            .notes_repo
            .read_file(&rel)
            .map_err(AppError::Internal)?
            .unwrap_or_default();
        let fm = Frontmatter::parse(&text);
        PipelineItem::from_frontmatter(note_id, &fm).ok_or_else(|| {
            AppError::Internal(anyhow::anyhow!(
                "created note did not parse as a pipeline item"
            ))
        })
    }

    #[tool(
        description = "Create a new pipeline item note under pipeline/ from company+kind \
                       (slugs the id, optional role appended). Writes the frontmatter note (+ \
                       optional body) through the collab room. Fails if it already exists."
    )]
    async fn create_pipeline_item(
        &self,
        Parameters(args): Parameters<CreatePipelineArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        let user = require_user(&ctx)?;
        let Some(kind) = Kind::parse(&args.kind) else {
            return Ok(CallToolResult::error(vec![ContentBlock::text(
                "kind must be 'lead' or 'application'",
            )]));
        };
        let kind_str = match kind {
            Kind::Lead => "lead",
            Kind::Application => "application",
        };
        let company = args.company.trim();
        if company.is_empty() {
            return Ok(CallToolResult::error(vec![ContentBlock::text(
                "company is required",
            )]));
        }
        let title = match args
            .role
            .as_deref()
            .map(str::trim)
            .filter(|s| !s.is_empty())
        {
            Some(role) => format!("{PIPELINE_PREFIX}{company} {role}"),
            None => format!("{PIPELINE_PREFIX}{company}"),
        };
        let note_id = slugify_note_id(&title);
        if note_id.is_empty() {
            return Ok(CallToolResult::error(vec![ContentBlock::text(
                "could not derive a note id from company/role",
            )]));
        }
        match self.create_pipeline(&user, &note_id, kind_str, &args).await {
            Ok(item) => json_ok(&item),
            Err(e) => Ok(app_error_to_tool(e)),
        }
    }

    #[tool(
        description = "Update frontmatter fields on an existing pipeline item (merge; untouched \
                       keys kept). Writes through the collab room."
    )]
    async fn update_pipeline_item(
        &self,
        Parameters(args): Parameters<UpdatePipelineArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        let user = require_user(&ctx)?;
        if !args.id.starts_with(PIPELINE_PREFIX) {
            return Ok(CallToolResult::error(vec![ContentBlock::text(
                "id must be a pipeline/ note",
            )]));
        }
        if let Err(e) = self.authorize_write(&user, &args.id).await {
            return Ok(app_error_to_tool(e));
        }
        let fields = args.frontmatter_updates();
        let id = args.id.clone();
        let applied = edit_note_through_room(&self.state, &args.id, &user, move |old| {
            let mut fm = Frontmatter::parse(old);
            for (key, value) in &fields {
                fm.set(key, value);
            }
            Some(fm.render())
        })
        .await
        .map_err(|e| McpError::internal_error(e.to_string(), None))?;
        if applied {
            json_ok(&json!({ "id": id, "updated": true }))
        } else {
            Ok(CallToolResult::error(vec![ContentBlock::text(
                "update was refused",
            )]))
        }
    }

    #[tool(
        description = "Log a timeline event on a pipeline item: prepends `- <today> — <line>` \
                       under the body `## Timeline`, and applies any of \
                       ball/expected_at/stage/next_action. Writes through the collab room."
    )]
    async fn log_pipeline_event(
        &self,
        Parameters(args): Parameters<LogPipelineEventArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        let user = require_user(&ctx)?;
        if !args.id.starts_with(PIPELINE_PREFIX) {
            return Ok(CallToolResult::error(vec![ContentBlock::text(
                "id must be a pipeline/ note",
            )]));
        }
        if let Err(e) = self.authorize_write(&user, &args.id).await {
            return Ok(app_error_to_tool(e));
        }
        let line = args.line.trim().to_string();
        if line.is_empty() {
            return Ok(CallToolResult::error(vec![ContentBlock::text(
                "line must not be empty",
            )]));
        }
        let entry = format!("- {} — {}", today_string(), line);

        let mut fields: Vec<(&'static str, String)> = Vec::new();
        if let Some(v) = args
            .ball
            .as_deref()
            .map(str::trim)
            .filter(|s| !s.is_empty())
        {
            fields.push(("ball", v.to_ascii_lowercase()));
        }
        for (key, val) in [
            ("expected_at", &args.expected_at),
            ("stage", &args.stage),
            ("next_action", &args.next_action),
        ] {
            if let Some(v) = val.as_deref().map(str::trim).filter(|s| !s.is_empty()) {
                fields.push((key, v.to_string()));
            }
        }

        let id = args.id.clone();
        let applied = edit_note_through_room(&self.state, &args.id, &user, move |old| {
            let mut fm = Frontmatter::parse(old);
            for (key, value) in &fields {
                fm.set(key, value);
            }
            fm.body = prepend_timeline(&fm.body, &entry);
            Some(fm.render())
        })
        .await
        .map_err(|e| McpError::internal_error(e.to_string(), None))?;
        if applied {
            json_ok(&json!({ "id": id, "logged": true }))
        } else {
            Ok(CallToolResult::error(vec![ContentBlock::text(
                "log was refused",
            )]))
        }
    }
}

#[tool_handler]
impl ServerHandler for McpServer {
    fn get_info(&self) -> ServerConfig {
        ServerConfig::new(
            ServerCapabilities::builder()
                .enable_tools()
                .enable_resources()
                .build(),
        )
        .with_instructions(
            "rust_note MCP server: read and update notes, todos, and daily stats. \
             Read the stats://docs and todo://grammar resources to learn the formats.",
        )
    }

    async fn list_resources(
        &self,
        _request: Option<PaginatedRequestParams>,
        _ctx: RequestContext<RoleServer>,
    ) -> Result<ListResourcesResult, McpError> {
        Ok(ListResourcesResult {
            resources: vec![
                Resource::new("stats://docs", "Stats format & API reference")
                    .with_mime_type("text/markdown"),
                Resource::new("todo://grammar", "Todo task-line grammar")
                    .with_mime_type("text/markdown"),
            ],
            ..Default::default()
        })
    }

    async fn list_resource_templates(
        &self,
        _request: Option<PaginatedRequestParams>,
        _ctx: RequestContext<RoleServer>,
    ) -> Result<ListResourceTemplatesResult, McpError> {
        Ok(ListResourceTemplatesResult {
            resource_templates: vec![
                ResourceTemplate::new("note://{id}", "Note by id").with_mime_type("text/markdown")
            ],
            ..Default::default()
        })
    }

    async fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        ctx: RequestContext<RoleServer>,
    ) -> Result<ReadResourceResponse, McpError> {
        let uri = request.uri;
        let contents = match uri.as_str() {
            "stats://docs" => {
                ResourceContents::text(crate::stats::routes::docs_markdown(), uri.clone())
            }
            "todo://grammar" => ResourceContents::text(TODO_GRAMMAR, uri.clone()),
            other => {
                let Some(id) = other.strip_prefix("note://") else {
                    return Err(McpError::resource_not_found(
                        "unknown resource",
                        Some(json!({ "uri": uri })),
                    ));
                };
                if is_settings_id(id) {
                    return Err(McpError::resource_not_found("not found", None));
                }
                let user = require_user(&ctx)?;
                match crate::notes::routes::get_note(
                    State(self.state.clone()),
                    RequireAuth(user),
                    Path(id.to_string()),
                )
                .await
                {
                    Ok(Json(resp)) => ResourceContents::text(resp.content, uri.clone()),
                    Err(_) => {
                        return Err(McpError::resource_not_found(
                            "note not found",
                            Some(json!({ "uri": uri })),
                        ))
                    }
                }
            }
        };
        Ok(ReadResourceResult::new(vec![contents]).into())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::auth::oidc::OidcClient;
    use crate::config::Config;
    use crate::notes::repo::NotesRepo;
    use axum_extra::extract::cookie::Key;
    use std::sync::Arc;

    async fn test_server() -> (McpServer, tempfile::TempDir, tempfile::TempDir) {
        let notes_dir = tempfile::tempdir().unwrap();
        let db_dir = tempfile::tempdir().unwrap();
        let db_path = db_dir.path().join("test.db");
        let notes_repo = NotesRepo::open_or_init(notes_dir.path().to_str().unwrap()).unwrap();
        let db = crate::db::init_pool(db_path.to_str().unwrap())
            .await
            .unwrap();
        sqlx::query(
            "INSERT INTO users (id, email, display_name, created_at) \
             VALUES ('alice', 'a@e', 'Alice', '2026-01-01T00:00:00Z')",
        )
        .execute(&db)
        .await
        .unwrap();
        let state = AppState {
            db,
            notes_repo,
            config: Arc::new(Config::from_env()),
            oidc: None::<Arc<OidcClient>>,
            cookie_key: Key::generate(),
            note_locks: crate::state::NoteLocks::new(),
            rooms: crate::collab::room::RoomRegistry::new(),
        };
        (McpServer::new(state), notes_dir, db_dir)
    }

    #[test]
    fn settings_ids_are_recognized() {
        assert!(is_settings_id("_settings"));
        assert!(is_settings_id("_settings/alice/main"));
        assert!(!is_settings_id("diary/2026-09-29"));
        assert!(!is_settings_id("notes/_settings"));
    }

    #[tokio::test]
    async fn note_index_excludes_settings_notes() {
        let (server, _n, _d) = test_server().await;
        for (id, content) in [
            ("diary/2026-09-01", "# Sept 1\n"),
            (
                "_settings/alice/main",
                "---\ntimezone: Europe/Warsaw\n---\n",
            ),
        ] {
            let rel = crate::notes::fs_store::note_id_to_path(id);
            crate::notes::acl::ensure_note_registered(&server.state.db, id, "alice")
                .await
                .unwrap();
            server
                .state
                .notes_repo
                .write_and_commit(&rel, content, "alice", "a@e", "seed")
                .await
                .unwrap();
        }
        let index = server.note_index("alice".to_string()).await.unwrap();
        let ids: Vec<&str> = index.iter().filter_map(|v| v["id"].as_str()).collect();
        assert!(
            ids.contains(&"diary/2026-09-01"),
            "normal note should be listed, got {ids:?}"
        );
        assert!(
            !ids.iter().any(|id| id.starts_with("_settings")),
            "settings notes must be excluded, got {ids:?}"
        );
    }

    #[test]
    fn append_markdown_adds_separator_and_trailing_newline() {
        assert_eq!(append_markdown("a", "b"), "a\nb\n");
        assert_eq!(append_markdown("a\n", "b\n"), "a\nb\n");
        assert_eq!(append_markdown("", "b"), "b\n");
    }

    #[test]
    fn set_checkbox_state_flips_marker() {
        assert_eq!(set_checkbox_state("- [ ] x", true).unwrap(), "- [x] x");
        assert_eq!(set_checkbox_state("- [x] x", false).unwrap(), "- [ ] x");
        assert!(set_checkbox_state("no checkbox here", true).is_none());
    }

    #[test]
    fn toggle_in_text_locates_and_flips() {
        let doc = "# Day\n- [ ] water plants\n- [ ] book flights #fb\n";
        // by text + correct line hint
        let out = toggle_in_text(doc, Some(2), "water plants", true).expect("match");
        assert!(out.contains("- [x] water plants"));
        assert!(out.contains("- [ ] book flights"));
        // idempotent when already in the desired state
        assert_eq!(
            toggle_in_text(&out, None, "water plants", true).unwrap(),
            out
        );
        // reopen
        assert!(toggle_in_text(&out, None, "water plants", false)
            .unwrap()
            .contains("- [ ] water plants"));
        // stale line hint falls back to a text match (text_clean form)
        assert!(toggle_in_text(doc, Some(99), "book flights", true)
            .unwrap()
            .contains("- [x] book flights"));
        // no match refuses
        assert!(toggle_in_text(doc, None, "nonexistent task", true).is_none());
    }

    #[tokio::test]
    async fn append_through_room_lands_on_disk() {
        let (server, _n, _d) = test_server().await;
        let rel = note_id_to_path("notes/foo");
        acl::ensure_note_registered(&server.state.db, "notes/foo", "alice")
            .await
            .unwrap();
        server
            .state
            .notes_repo
            .write_and_commit(&rel, "# Foo\n", "alice", "a@e", "seed")
            .await
            .unwrap();

        server.authorize_write("alice", "notes/foo").await.unwrap();
        let applied = edit_note_through_room(&server.state, "notes/foo", "alice", |old| {
            Some(append_markdown(old, "appended line"))
        })
        .await
        .unwrap();
        assert!(applied);

        let text = server.state.notes_repo.read_file(&rel).unwrap().unwrap();
        assert!(text.contains("# Foo"), "original kept: {text:?}");
        assert!(text.contains("appended line"), "append landed: {text:?}");
    }

    #[tokio::test]
    async fn authorize_write_denies_another_users_note() {
        let (server, _n, _d) = test_server().await;
        sqlx::query(
            "INSERT INTO users (id, email, display_name, created_at) \
             VALUES ('bob', NULL, NULL, '2026-01-01T00:00:00Z')",
        )
        .execute(&server.state.db)
        .await
        .unwrap();
        let rel = note_id_to_path("notes/bob-note");
        acl::ensure_note_registered(&server.state.db, "notes/bob-note", "bob")
            .await
            .unwrap();
        server
            .state
            .notes_repo
            .write_and_commit(&rel, "secret\n", "bob", "b@e", "seed")
            .await
            .unwrap();

        let res = server.authorize_write("alice", "notes/bob-note").await;
        assert!(matches!(res, Err(AppError::Forbidden)), "got {res:?}");
    }

    #[tokio::test]
    async fn authorize_write_missing_note_is_not_found() {
        let (server, _n, _d) = test_server().await;
        let res = server
            .authorize_write("alice", "notes/does-not-exist")
            .await;
        assert!(matches!(res, Err(AppError::NotFound)), "got {res:?}");
    }
}
