//! The MCP server handler: the tool + resource surface.
//!
//! Tools are declared with rmcp's `#[tool_router]`/`#[tool]`/`#[tool_handler]`
//! macros. Every handler resolves the request's authenticated user (injected by
//! [`super::auth`]) and delegates to the same ACL-checked handlers the REST
//! routes use, constructing their axum extractors directly — so the MCP surface
//! and the HTTP surface share one implementation and one permission model.

use axum::extract::{Path, Query, State};
use axum::Json;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::{
    CallToolResult, ContentBlock, ListResourceTemplatesResult, ListResourcesResult,
    PaginatedRequestParams, ReadResourceRequestParams, ReadResourceResponse, ReadResourceResult,
    Resource, ResourceContents, ResourceTemplate, ServerCapabilities, ServerConfig,
};
use rmcp::service::RequestContext;
use rmcp::{tool, tool_handler, tool_router, ErrorData as McpError, RoleServer, ServerHandler};
use serde::Deserialize;
use serde_json::json;

use super::auth::AuthUser;
use crate::auth::session::RequireAuth;
use crate::error::AppError;
use crate::state::AppState;

/// One MCP server instance. A fresh one is built per session by the service
/// factory (see [`super::service`]), each capturing process-wide [`AppState`].
///
/// Note there is deliberately no `tool_router` field: rmcp's `#[tool_handler]`
/// dispatches through the *static* `Self::tool_router()` (generated by
/// `#[tool_router]`), so an instance field would be dead weight.
pub struct McpServer {
    state: AppState,
}

// ---- request-scoped identity ----------------------------------------------

/// Pull the authenticated `user_id` the auth middleware stashed. The rmcp
/// transport forwards the whole `http::request::Parts` into the request
/// context; our [`AuthUser`] lives inside its extensions.
fn require_user(ctx: &RequestContext<RoleServer>) -> Result<String, McpError> {
    let parts = ctx
        .extensions
        .get::<axum::http::request::Parts>()
        .ok_or_else(|| McpError::internal_error("missing request context", None))?;
    let user = parts
        .extensions
        .get::<AuthUser>()
        .ok_or_else(|| McpError::invalid_params("unauthenticated", None))?;
    Ok(user.0.clone())
}

// ---- result helpers -------------------------------------------------------

/// Wrap a serializable value as a single JSON text content block.
fn json_ok<T: serde::Serialize>(value: &T) -> Result<CallToolResult, McpError> {
    let text = serde_json::to_string_pretty(value)
        .map_err(|e| McpError::internal_error(format!("serialize: {e}"), None))?;
    Ok(CallToolResult::success(vec![ContentBlock::text(text)]))
}

/// Map an [`AppError`] to a client-visible tool error, mirroring the REST
/// error mapping (internal details are logged, never leaked to the client).
fn app_error_to_tool(err: AppError) -> CallToolResult {
    if let AppError::Internal(e) = &err {
        tracing::error!(error = ?e, "mcp tool internal error");
    }
    let message = match &err {
        AppError::Internal(_) => "internal error".to_string(),
        other => other.to_string(),
    };
    CallToolResult::error(vec![ContentBlock::text(message)])
}

/// Settings notes (`_settings/<user>/…`) hold secrets (OpenRouter key) and app
/// internals; they are never exposed through the MCP surface.
fn is_settings_id(id: &str) -> bool {
    id == "_settings" || id.starts_with("_settings/")
}

/// The task-line grammar, exposed as the `todo://grammar` resource so a client
/// LLM can author valid tasks and build filters without a server round-trip.
const TODO_GRAMMAR: &str = "\
# rust_note task-line grammar

Tasks are markdown checkbox lines inside a note (daily notes are `diary/YYYY-MM-DD`):

    - [ ] open task   ·   - [x] done task

Inline tokens (any order, after the text):
- Burner priority via a tag: `#fb` / `#frontburner`, `#bb` / `#backburner`, `#fridge`, `#oven`.
  Front burner = do now; back burner = soon; fridge = someday (ages/\"spoils\" after 14 days);
  oven = parked.
- `p:N`   pomodoros estimate (integer). NOTE: unrelated to YAML `pomodoros` stats.
- `start:HH:MM`   start time.
- `due:<text>`   due date/time (free text to end of line).
- `#tag`   arbitrary tags.
- `@location`   context, e.g. `@home`, `@work`, `@store` (lowercased).

Example:
    - [ ] draft the proposal #fb p:3 start:09:00 due:friday #work @office

Query/filter tokens (for the `search_notes`/board style search, applied client-side):
`@loc`, `#tag`, burner names (`fb`/`frontburner`/`bb`/`backburner`/`fridge`/`oven`),
`p>=N` / `p<=N`, and free text.";

// ---- tool argument types --------------------------------------------------

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct SearchNotesArgs {
    /// Case-insensitive substring matched against each note's id and title.
    query: String,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct ReadNoteArgs {
    /// Note id, e.g. `diary/2026-09-29` or `projects/trip-planning`.
    id: String,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct ListTodosArgs {
    /// `diary` (default) restricts to daily notes; `all` scans every note.
    #[serde(default)]
    scope: Option<String>,
    /// Include completed tasks. Defaults to true.
    #[serde(default)]
    include_done: Option<bool>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct GetStatsArgs {
    /// Inclusive start date `YYYY-MM-DD`. Defaults to 30 days before `to`.
    #[serde(default)]
    from: Option<String>,
    /// Inclusive end date `YYYY-MM-DD`. Defaults to today (server timezone).
    #[serde(default)]
    to: Option<String>,
    /// Restrict to one metric. A parent name (e.g. `exercise`) returns a
    /// boolean "did it happen" series. Omit for the whole registered dashboard.
    #[serde(default)]
    metric: Option<String>,
}

#[tool_router]
impl McpServer {
    pub fn new(state: AppState) -> Self {
        Self { state }
    }

    /// Fetch the caller's readable note metadata, minus settings notes.
    async fn note_index(&self, user_id: String) -> Result<Vec<serde_json::Value>, McpError> {
        let Json(metas) =
            crate::notes::routes::list_notes(State(self.state.clone()), RequireAuth(user_id))
                .await
                .map_err(|e| match e {
                    AppError::Internal(err) => {
                        McpError::internal_error(format!("list notes: {err}"), None)
                    }
                    other => McpError::internal_error(other.to_string(), None),
                })?;
        Ok(metas
            .into_iter()
            .filter(|m| !is_settings_id(&m.id))
            .map(|m| json!({ "id": m.id, "title": m.title, "updated_at": m.updated_at }))
            .collect())
    }

    #[tool(
        description = "List all notes the user can read, as {id, title, updated_at} (no bodies)."
    )]
    async fn list_notes(
        &self,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        let user = require_user(&ctx)?;
        let index = self.note_index(user).await?;
        json_ok(&index)
    }

    #[tool(
        description = "Find notes whose id or title contains a substring (case-insensitive). \
                          Title/id search only — not full-text."
    )]
    async fn search_notes(
        &self,
        Parameters(args): Parameters<SearchNotesArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        let user = require_user(&ctx)?;
        let needle = args.query.to_lowercase();
        let matches: Vec<serde_json::Value> = self
            .note_index(user)
            .await?
            .into_iter()
            .filter(|m| {
                let hay = |k: &str| {
                    m.get(k)
                        .and_then(|v| v.as_str())
                        .map(|s| s.to_lowercase().contains(&needle))
                        .unwrap_or(false)
                };
                hay("id") || hay("title")
            })
            .collect();
        json_ok(&matches)
    }

    #[tool(description = "Read one note's content and metadata by id.")]
    async fn read_note(
        &self,
        Parameters(args): Parameters<ReadNoteArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        let user = require_user(&ctx)?;
        if is_settings_id(&args.id) {
            return Ok(CallToolResult::error(vec![ContentBlock::text(
                "settings notes are not accessible via MCP",
            )]));
        }
        match crate::notes::routes::get_note(
            State(self.state.clone()),
            RequireAuth(user),
            Path(args.id),
        )
        .await
        {
            Ok(Json(resp)) => json_ok(&resp),
            Err(e) => Ok(app_error_to_tool(e)),
        }
    }

    #[tool(
        description = "List parsed tasks across notes (burner, pomodoros, start/due, tags, \
                          locations, done). Filter client-side; see the todo://grammar resource."
    )]
    async fn list_todos(
        &self,
        Parameters(args): Parameters<ListTodosArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        use crate::todos::routes::{Scope, TodosQuery};
        let user = require_user(&ctx)?;
        let scope = match args.scope.as_deref() {
            Some("all") => Scope::All,
            _ => Scope::Diary,
        };
        let query = TodosQuery {
            scope,
            include_done: args.include_done.unwrap_or(true),
        };
        match crate::todos::routes::list_todos(
            State(self.state.clone()),
            RequireAuth(user),
            Query(query),
        )
        .await
        {
            Ok(Json(todos)) => json_ok(&todos),
            Err(e) => Ok(app_error_to_tool(e)),
        }
    }

    #[tool(
        description = "Get daily stat series over a date range (per-day aggregated value plus \
                          raw timed points). A parent metric name returns a boolean series."
    )]
    async fn get_stats(
        &self,
        Parameters(args): Parameters<GetStatsArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        use crate::stats::routes::StatsQuery;
        let user = require_user(&ctx)?;
        let query = StatsQuery {
            from: args.from,
            to: args.to,
            metric: args.metric,
        };
        match crate::stats::routes::list_stats(
            State(self.state.clone()),
            RequireAuth(user),
            Query(query),
        )
        .await
        {
            Ok(Json(resp)) => json_ok(&resp),
            Err(e) => Ok(app_error_to_tool(e)),
        }
    }

    #[tool(
        description = "List the user's registered stat metrics (metric, unit, label, chart, agg)."
    )]
    async fn list_metrics(
        &self,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        let user = require_user(&ctx)?;
        match crate::stats::routes::get_registry(State(self.state.clone()), RequireAuth(user)).await
        {
            Ok(Json(defs)) => json_ok(&defs),
            Err(e) => Ok(app_error_to_tool(e)),
        }
    }
}

#[tool_handler]
impl ServerHandler for McpServer {
    fn get_info(&self) -> ServerConfig {
        ServerConfig::new(
            ServerCapabilities::builder()
                .enable_tools()
                .enable_resources()
                .build(),
        )
        .with_instructions(
            "rust_note MCP server: read and update notes, todos, and daily stats. \
             Read the stats://docs and todo://grammar resources to learn the formats.",
        )
    }

    async fn list_resources(
        &self,
        _request: Option<PaginatedRequestParams>,
        _ctx: RequestContext<RoleServer>,
    ) -> Result<ListResourcesResult, McpError> {
        Ok(ListResourcesResult {
            resources: vec![
                Resource::new("stats://docs", "Stats format & API reference")
                    .with_mime_type("text/markdown"),
                Resource::new("todo://grammar", "Todo task-line grammar")
                    .with_mime_type("text/markdown"),
            ],
            ..Default::default()
        })
    }

    async fn list_resource_templates(
        &self,
        _request: Option<PaginatedRequestParams>,
        _ctx: RequestContext<RoleServer>,
    ) -> Result<ListResourceTemplatesResult, McpError> {
        Ok(ListResourceTemplatesResult {
            resource_templates: vec![
                ResourceTemplate::new("note://{id}", "Note by id").with_mime_type("text/markdown")
            ],
            ..Default::default()
        })
    }

    async fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        ctx: RequestContext<RoleServer>,
    ) -> Result<ReadResourceResponse, McpError> {
        let uri = request.uri;
        let contents = match uri.as_str() {
            "stats://docs" => {
                ResourceContents::text(crate::stats::routes::docs_markdown(), uri.clone())
            }
            "todo://grammar" => ResourceContents::text(TODO_GRAMMAR, uri.clone()),
            other => {
                let Some(id) = other.strip_prefix("note://") else {
                    return Err(McpError::resource_not_found(
                        "unknown resource",
                        Some(json!({ "uri": uri })),
                    ));
                };
                if is_settings_id(id) {
                    return Err(McpError::resource_not_found("not found", None));
                }
                let user = require_user(&ctx)?;
                match crate::notes::routes::get_note(
                    State(self.state.clone()),
                    RequireAuth(user),
                    Path(id.to_string()),
                )
                .await
                {
                    Ok(Json(resp)) => ResourceContents::text(resp.content, uri.clone()),
                    Err(_) => {
                        return Err(McpError::resource_not_found(
                            "note not found",
                            Some(json!({ "uri": uri })),
                        ))
                    }
                }
            }
        };
        Ok(ReadResourceResult::new(vec![contents]).into())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::auth::oidc::OidcClient;
    use crate::config::Config;
    use crate::notes::repo::NotesRepo;
    use axum_extra::extract::cookie::Key;
    use std::sync::Arc;

    async fn test_server() -> (McpServer, tempfile::TempDir, tempfile::TempDir) {
        let notes_dir = tempfile::tempdir().unwrap();
        let db_dir = tempfile::tempdir().unwrap();
        let db_path = db_dir.path().join("test.db");
        let notes_repo = NotesRepo::open_or_init(notes_dir.path().to_str().unwrap()).unwrap();
        let db = crate::db::init_pool(db_path.to_str().unwrap())
            .await
            .unwrap();
        sqlx::query(
            "INSERT INTO users (id, email, display_name, created_at) \
             VALUES ('alice', 'a@e', 'Alice', '2026-01-01T00:00:00Z')",
        )
        .execute(&db)
        .await
        .unwrap();
        let state = AppState {
            db,
            notes_repo,
            config: Arc::new(Config::from_env()),
            oidc: None::<Arc<OidcClient>>,
            cookie_key: Key::generate(),
            note_locks: crate::state::NoteLocks::new(),
            rooms: crate::collab::room::RoomRegistry::new(),
        };
        (McpServer::new(state), notes_dir, db_dir)
    }

    #[test]
    fn settings_ids_are_recognized() {
        assert!(is_settings_id("_settings"));
        assert!(is_settings_id("_settings/alice/main"));
        assert!(!is_settings_id("diary/2026-09-29"));
        assert!(!is_settings_id("notes/_settings"));
    }

    #[tokio::test]
    async fn note_index_excludes_settings_notes() {
        let (server, _n, _d) = test_server().await;
        for (id, content) in [
            ("diary/2026-09-01", "# Sept 1\n"),
            (
                "_settings/alice/main",
                "---\ntimezone: Europe/Warsaw\n---\n",
            ),
        ] {
            let rel = crate::notes::fs_store::note_id_to_path(id);
            crate::notes::acl::ensure_note_registered(&server.state.db, id, "alice")
                .await
                .unwrap();
            server
                .state
                .notes_repo
                .write_and_commit(&rel, content, "alice", "a@e", "seed")
                .await
                .unwrap();
        }
        let index = server.note_index("alice".to_string()).await.unwrap();
        let ids: Vec<&str> = index.iter().filter_map(|v| v["id"].as_str()).collect();
        assert!(
            ids.contains(&"diary/2026-09-01"),
            "normal note should be listed, got {ids:?}"
        );
        assert!(
            !ids.iter().any(|id| id.starts_with("_settings")),
            "settings notes must be excluded, got {ids:?}"
        );
    }
}
